image: 
- macOS
- Visual Studio 2022
- Ubuntu2204

environment:
  major: 4
  minor: 0
  release: 0
  app_version: '$(major).$(minor).$(release).$(APPVEYOR_BUILD_NUMBER)'

version: '$(major).$(minor).$(release).{build}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  assembly_version: '$(app_version)'
  file_version: '$(app_version)'
  informational_version: '$(app_version)'

build_script:
  # windows
  - cmd: msbuild OSPSuite.SimModel.sln /property:Configuration=Debug;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild OSPSuite.SimModel.sln /property:Configuration=Release;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # linux release build
  - sh: cmake -BBuild/Release/x64/ -Hsrc/OSPSuite.SimModelNative/ -DCMAKE_BUILD_TYPE=Release -DFuncParserDir=Build/Release/x64/
  - sh: cp packages/OSPSuite.FuncParser.Ubuntu22/OSPSuite.FuncParserNative/bin/native/x64/Release/libOSPSuite.FuncParserNative.so Build/Release/x64/
  - sh: cp packages/OSPSuite.SimModelSolver_CVODES.Ubuntu22/OSPSuite.SimModelSolver_CVODES/bin/native/x64/Release/libOSPSuite.SimModelSolver_CVODES.so Build/Release/x64/
  - sh: make -C Build/Release/x64/
  - sh: dotnet build OSPSuite.SimModel.sln /property:Configuration=Release;Platform=x64
  - sh: export LD_LIBRARY_PATH=Build/Release/x64/:$LD_LIBRARY_PATH
  # linux debug build
  - sh: cmake -BBuild/Debug/x64/ -Hsrc/OSPSuite.SimModelNative/ -DCMAKE_BUILD_TYPE=Debug -DFuncParserDir=Build/Debug/x64/
  - sh: cp packages/OSPSuite.FuncParser.Ubuntu22/OSPSuite.FuncParserNative/bin/native/x64/Debug/libOSPSuite.FuncParserNative.so Build/Debug/x64/
  - sh: cp packages/OSPSuite.SimModelSolver_CVODES.Ubuntu22/OSPSuite.SimModelSolver_CVODES/bin/native/x64/Debug/libOSPSuite.SimModelSolver_CVODES.so Build/Debug/x64/
  - sh: make -C Build/Debug/x64/
  - sh: dotnet build OSPSuite.SimModel.sln /property:Configuration=Debug;Platform=x64

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - git submodule update --init --recursive
  - nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
  - nuget sources add -name utility -source https://ci.appveyor.com/nuget/ospsuite-utility 
  - nuget sources add -name funcparser -source https://ci.appveyor.com/nuget/ospsuite-funcparser 
  - nuget sources add -name cvodes -source https://ci.appveyor.com/nuget/ospsuite-simmodel-solver-cvodes
  - nuget sources add -name centos -source https://ci.appveyor.com/nuget/ospsuite-centos
  - ps: (get-content src\OSPSuite.SimModelNative\version.h) | foreach-object {$_ -replace "RELEASE 0", "RELEASE $env:RELEASE" -replace "MAJOR 0", "MAJOR $env:MAJOR" -replace "MINOR 0", "MINOR $env:MINOR" -replace "BUILD 0", "BUILD $env:APPVEYOR_BUILD_NUMBER"} | set-content src\OSPSuite.SimModelNative\version.h
  - sh: nuget install packages.config -OutputDirectory packages -ExcludeVersion
  - dotnet restore --source https://ci.appveyor.com/nuget/ospsuite-centos --source https://ci.appveyor.com/nuget/ospsuite-simmodel-solver-cvodes --source https://ci.appveyor.com/nuget/ospsuite-funcparser --source https://ci.appveyor.com/nuget/ospsuite-bddhelper --source https://ci.appveyor.com/nuget/ospsuite-utility --source https://www.nuget.org/api/v2/
  - dotnet add tests/OSPSuite.SimModel.Tests/OSPSuite.SimModel.Tests.csproj package Appveyor.TestLogger --version 2.0.0
  # linux: remove all native c++ projects and test application from the solution
  - sh: dotnet sln OSPSuite.SimModel.sln remove src/OSPSuite.SimModelNative/OSPSuite.SimModelNative.vcxproj
  - sh: dotnet sln OSPSuite.SimModel.sln remove src/OSPSuite.SysTool/OSPSuite.SysTool.vcxproj
  - sh: dotnet sln OSPSuite.SimModel.sln remove src/OSPSuite.XMLWrapper/OSPSuite.XMLWrapper.vcxproj
  - sh: dotnet sln OSPSuite.SimModel.sln remove tests/TestAppNetCore/TestAppNetCore.csproj
#  - sh: sudo update-alternatives --set gcc /usr/bin/gcc-7

install:
  #linux: install libxml2
  # - sh: sudo apt-get update --assume-yes 
  - sh: sudo apt-get install libxml2-dev --assume-yes 
 
after_build:
  - cmd: dotnet pack src/OSPSuite.SimModel/ -p:PackageVersion=%app_version% -o ./
  - sh: dotnet pack src/OSPSuite.SimModel/ -p:PackageVersion=%app_version% -o ./
  - ps: Get-ChildItem .\OSPSuite.SimModel.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

test_script:
  - ps: dotnet test --no-build --no-restore --logger:Appveyor --configuration:Release --verbosity normal 

branches:
  only:
    - master
    - develop

skip_commits:
  files:
    - '*.md'

skip_tags: true

pull_requests: 
  do_not_increment_build_number: true     

nuget: 
  disable_publish_on_pr: true  

notifications:
  - provider: Slack
    incoming_webhook:      
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyF1h7st5qNdNezFp6T+bWXqrcZ4q/smtPcJ7LkUFHL46JDYUFlIL8FDz+ApX/vP+x0=
