name: Build and Publish NuGet Package for all supported platforms

on:
  push:
    branches:
    - master

permissions:
  packages: write

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      app_version: 5.0.0.${{ github.run_number }}
      publish: true
    secrets: inherit
