name: Build and Publish NuGet Package for all supported platforms

on:
  push:
  pull_request:
    branches:
    - master

permissions:
  packages: write

env:
  MAJOR: 4
  MINOR: 0
  RELEASE: 0
  RUN: ${{ github.run_number }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      BUILD_ID: ${{ steps.get_build_id.outputs.BUILD_ID}}
      APP_VERSION: ${{ steps.get_app_version.outputs.APP_VERSION}}
    steps:
    - name: Get New Build Number
      id: get_build_id
      shell: bash
      run: |

        # Get the build ID
        if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ]]; then
          # Fetch the latest version from the organization NuGet package
          response=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/Open-Systems-Pharmacology/packages/nuget/OSPSuite.SimModel/versions)

          # Log the raw response for debugging
          echo "API Response: $response"

          # Check if the response indicates a package not found error or is not valid JSON
          if echo "$response" | jq -e '.message == "Package not found." or (.[0].name // empty | length == 0)' >/dev/null 2>&1; then
            # exit with error code when a next build number cannot be established
            exit 1
          else
            latest_version=$(echo "$response" | jq -r '.[0].name // empty')
            
            # Extract MAJOR, MINOR, and RELEASE from the latest version
            IFS='.' read -r last_major last_minor last_release last_build <<< "$latest_version"
            
            # Compare with the current MAJOR, MINOR, and RELEASE
            if [[ "$last_major" -eq "${{ env.MAJOR }}" && "$last_minor" -eq "${{ env.MINOR }}" && "$last_release" -eq "${{ env.RELEASE }}" ]]; then
              # Increment the last number if they match
              new_build_id=$((last_build + 1))
            else
              # Reset build number to 0 if the current version is different
              new_build_id=0
            fi
          fi

          echo "latest build number: ${latest_version:-'None found'}"
          echo "new build number: ${new_build_id}"
          build_id="${new_build_id}"
        else
          build_id="999${{ env.RUN }}"
        fi
        
        echo "New Build ID: ${build_id}"
        echo "BUILD_ID=${build_id}" >> $GITHUB_ENV
        echo "BUILD_ID=${build_id}" >> $GITHUB_OUTPUT
      
    - name: Get App Version
      id: get_app_version
      shell: bash
      run: |
        app_version="${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.RELEASE }}.${{ env.BUILD_ID }}"
        echo "App Version: ${app_version}"
        echo "APP_VERSION=${app_version}" >> $GITHUB_ENV
        echo "APP_VERSION=${app_version}" >> $GITHUB_OUTPUT

  build-nix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: MacOS
            nuget_package: OSPSuite.SimModel.MacOSArm64
            version_h_modifier: "sed -i ''"
          - os: macos-13
            platform: MacOS
            nuget_package: OSPSuite.SimModel.MacOSx64
            version_h_modifier: "sed -i ''"
          - os: ubuntu-22.04
            platform: Ubuntu22
            nuget_package: OSPSuite.SimModel.Ubuntu22
            version_h_modifier: "sed -i"

    runs-on: ${{ matrix.os }}
    needs: get-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: define env variables
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"  --name OSP-GitHub-Packages --username Open-Systems-Pharmacology --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          echo "APP_VERSION=${{needs.get-version.outputs.APP_VERSION}}" >> $GITHUB_ENV
          echo "BUILD_ID=${{needs.get-version.outputs.BUILD_ID}}" >> $GITHUB_ENV

      - name: Update version.h
        run: |
          LC_ALL=C ${{ matrix.version_h_modifier }} -e "s@RELEASE 0@RELEASE ${{env.RELEASE}}@g" \
              -e "s@MAJOR 0@MAJOR ${{env.MAJOR}}@g" \
              -e "s@MINOR 0@MINOR ${{env.MINOR}}@g" \
              -e "s@BUILD 0@BUILD ${{ env.BUILD_ID }}@g" \
              src/OSPSuite.SimModelNative/version.h

      - name: Build Debug and Release
        run: ./buildNix.sh ${{matrix.platform}}  ${{env.APP_VERSION}}

      - name: Push nupkg as artifact
        # if it is a push to a branch
        if: github.event_name == 'push' && github.ref_name != github.event.repository.default_branch
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.nuget_package}}
          path: ./*.nupkg

      - name: Push test log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: testLog_${{matrix.os}}
          path: ./**/testLog*.html

      - name: Publish to GitHub registry
        # if it is a merge to default branch
        if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        run: dotnet nuget push ./*.nupkg --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{ secrets.GITHUB_TOKEN }}

  build-windows-x64:
    runs-on: windows-latest
    needs: get-version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: define env variables
        run: |
          echo "APP_VERSION=${{needs.get-version.outputs.APP_VERSION}}" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "BUILD_ID=${{needs.get-version.outputs.BUILD_ID}}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Restore dependencies
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"  --name OSP-GitHub-Packages --username Open-Systems-Pharmacology --password ${{ secrets.GITHUB_TOKEN }}
          dotnet restore

      - name: Update version.h
        shell: pwsh
        run: |
          (get-content src\OSPSuite.SimModelNative\version.h) | foreach-object {$_ -replace "RELEASE 0", "RELEASE ${{env.RELEASE}}" -replace "MAJOR 0", "MAJOR ${{env.MAJOR}}" -replace "MINOR 0", "MINOR ${{env.MINOR}}" -replace "BUILD 0", "BUILD ${{ env.BUILD_ID }}" } | set-content src\OSPSuite.SimModelNative\version.h

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Debug and Release
        run: ./buildWindows.bat ${{env.APP_VERSION}}

      - name: Push nupkg as artifact
        # if it is a push to a branch
        if: github.event_name == 'push' && github.ref_name != github.event.repository.default_branch
        uses: actions/upload-artifact@v4
        with:
          name: OSPSuite.SimModel
          path: ./*.nupkg

      - name: Push test log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: testLog_Windows
          path: ./**/testLog*.html
          
      - name: Publish to GitHub registry
        # if it is a merge to default branch
        if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        shell: pwsh
        run: dotnet nuget push OSPSuite.SimModel*.nupkg --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{ secrets.GITHUB_TOKEN }}